src/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views


urlpatterns = [
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # themoneyapp urls
    path("", include("themoneyapp.urls")),
    # themoneyapp_users urls
    path("users/", include("themoneyapp.users.urls")),
    # allauth urls
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
    # ...
    # Media files
    *static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT),
]

# API URLS
urlpatterns += [
    # API urls
    path("api/", include("config.api_router")),
]

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns = [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
        *urlpatterns,
    ]

    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [
            # URLs specific only to django-debug-toolbar:
            path("__debug__/", include(debug_toolbar.urls)),
            *urlpatterns,
        ]

src/themoneyapp/urls.py
"""URLs for themoneyapp application."""

from django.urls import path

from themoneyapp.core.views import ProtectedTemplateView


app_name = "themoneyapp"

urlpatterns = [
    path(
        "",
        ProtectedTemplateView.as_view(template_name="themoneyapp/index.html"),
        name="index",
    ),
]

src/themoneyapp/users/urls.py
"""URLs for themoneyapp.users application."""

from django.urls import path

from .views import user_detail_view, user_redirect_view, user_update_view


app_name = "themoneyapp_users"

urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<int:pk>/", view=user_detail_view, name="detail"),
]

src/themoneyapp/users/models.py
"""models for themoneyapp.users app."""

from __future__ import annotations

import typing as t

from django.contrib.auth.models import AbstractUser
from django.db.models import CharField, EmailField
from django.urls import reverse
from django.utils.translation import gettext_lazy as _

from .managers import UserManager


class User(AbstractUser):
    """Default custom user model for themoneyapp.

    If adding fields that need to be filled at user signup,
    check forms.SignupForm accordingly.
    """

    # First and last name do not cover name patterns around the globe
    name = CharField(_("Name of User"), blank=True, max_length=255)
    first_name = None  # type: ignore[assignment]
    last_name = None  # type: ignore[assignment]
    email = EmailField(_("email address"), blank=False, null=False, unique=True)
    username = None  # type: ignore[assignment]

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    objects: t.ClassVar[UserManager] = UserManager()

    def get_absolute_url(self) -> str:
        """Get URL for user's detail view.

        Returns:
            str: URL for user detail.

        """
        return reverse("themoneyapp_users:detail", kwargs={"pk": self.id})

src/themoneyapp/users/forms.py
"""forms for the themoneyapp.users application."""

from django.contrib.auth import forms as admin_forms
from django.forms import EmailField
from django.utils.translation import gettext_lazy as _

from allauth.account.forms import SignupForm

from .models import User


class UserAdminChangeForm(admin_forms.UserChangeForm[User]):
    """Form for User change in the Admin Area."""

    class Meta(admin_forms.UserChangeForm.Meta):  # type: ignore[name-defined]
        """Meta class for the UserAdminChangeForm form class."""

        model = User
        field_classes = {"email": EmailField}


class UserAdminCreationForm(admin_forms.UserCreationForm[User]):
    """Form for User Creation in the Admin Area.

    To change user signup, see UserSignupForm.
    """

    class Meta(admin_forms.UserCreationForm.Meta):  # type: ignore[name-defined]
        """Meta class for the UserAdminCreationForm form class."""

        model = User
        fields = ("email",)
        field_classes = {"email": EmailField}
        error_messages = {
            "email": {"unique": _("This email has already been taken.")},
        }


class UserSignupForm(SignupForm):
    """Form that will be rendered on a user sign up section/screen.

    Default fields will be added automatically.
    """

src/themoneyapp/core/views.py
"""Generic django views."""

from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import TemplateView


class ProtectedTemplateView(LoginRequiredMixin, TemplateView):
    """Template view which requires an authenticated user."""

src/themoneyapp/users/api/views.py
"""API views for the themoneyapp.users app."""

from __future__ import annotations

import typing as t

from django.db.models.query import QuerySet
from django.http import HttpRequest

from rest_framework import status
from rest_framework.decorators import action
from rest_framework.mixins import ListModelMixin, RetrieveModelMixin, UpdateModelMixin
from rest_framework.response import Response
from rest_framework.viewsets import GenericViewSet

from .serializers import UserSerializer
from themoneyapp.users.models import User


class UserViewSet(
    RetrieveModelMixin,
    ListModelMixin,
    UpdateModelMixin,
    GenericViewSet[User],
):
    """all drf views for the users."""

    serializer_class = UserSerializer
    queryset = User.objects.all()
    lookup_field = "pk"

    def get_queryset(self, *args: t.Any, **kwargs: t.Any) -> QuerySet[User]:  # noqa: ANN401
        """Queryset for the current authenticated user."""
        assert isinstance(self.request.user.id, int)
        return self.queryset.filter(id=self.request.user.id)

    @action(detail=False)
    def me(self, request: HttpRequest) -> Response:
        """Details for the current authenticated user."""
        serializer = UserSerializer(request.user, context={"request": request})  # type: ignore[arg-type]
        return Response(status=status.HTTP_200_OK, data=serializer.data)

src/themoneyapp/users/views.py
"""Views for the themoneyapp.users application."""

from __future__ import annotations

from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import AnonymousUser
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.views.generic import DetailView, RedirectView, UpdateView

from themoneyapp.users.models import User


class UserDetailView(LoginRequiredMixin, DetailView[User]):
    """View for user details."""

    model = User
    slug_field = "id"
    slug_url_kwarg = "id"


user_detail_view = UserDetailView.as_view()


class UserUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):  # type: ignore[type-arg]
    """View to update the user."""

    model = User
    fields = ["name"]
    success_message = _("Information successfully updated")

    def get_success_url(self) -> str:
        """Return the URL to redirect to after processing a valid form.

        Returns:
            str: url for the user detail view.
        """
        # for mypy to know that the user is authenticated
        assert self.request.user.is_authenticated
        return self.request.user.get_absolute_url()

    def get_object(self) -> User | AnonymousUser:  # type: ignore[override]
        """Get the current user to update.

        Returns:
            User | AnonymousUser: current authenticated/anonymous user.
        """
        return self.request.user


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):
    """View to redirect user on success login."""

    permanent = False

    def get_redirect_url(self) -> str:
        """Get the url to redirect to.

        Returns:
            str: URL for the index page of themoneyapp application.
        """
        return reverse("themoneyapp:index")


user_redirect_view = UserRedirectView.as_view()

src/themoneyapp/templates/403_csrf.html
{% extends "themoneyapp/_base.html" %}

{% block title %}
  Forbidden (403)
{% endblock title %}

{% block content %}
  <h1>Forbidden (403)</h1>
  <p>
    {% if exception %}
      {{ exception }}
    {% else %}
      You're not allowed to access this page.
    {% endif %}
  </p>
{% endblock content %}

src/themoneyapp/templates/_components/alert.html
{% load allauth %}

{% setvar color %}
  blue
{% endsetvar %}
{% setvar color_dark_weight %}
  400
{% endsetvar %}
{% if level == "error" %}
  {% setvar color %}
    red
  {% endsetvar %}
{% elif level == "success" %}
  {% setvar color %}
    green
  {% endsetvar %}
{% elif level == "warning" %}
  {% setvar color %}
    yellow
  {% endsetvar %}
  {% setvar color_dark_weight %}
    300
  {% endsetvar %}
{% elif level == "debug" %}
  {% setvar color %}
    gray
  {% endsetvar %}
  {% setvar color_dark_weight %}
    300
  {% endsetvar %}
{% endif %}
<div class="p-4 mb-4 text-sm text-{{ color }}-800 rounded-lg bg-{{ color }}-50 dark:bg-gray-800 dark:text-{{ color }}-{{ color_dark_weight }}"
     role="alert">{{ message }}</div>

src/themoneyapp/templates/_layouts/action_main.html
{% extends "_layouts/base.html" %}

{% block body %}
  {{ block.super }}

  {% block main %}
    <main class="bg-gray-50 dark:bg-gray-900">

      {% block main_container %}
        {% block main_content %}
        {% endblock main_content %}
      {% endblock main_container %}

    </main>
  {% endblock main %}
{% endblock body %}

src/themoneyapp/templates/_layouts/base.html
{% load render_bundle from webpack_loader %}
{% load i18n %}
{% load static %}

<!DOCTYPE html>
<html lang="en" class="dark">
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="x-ua-compatible" content="ie=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="description" content="Behold My Awesome Project!" />
    <meta name="author" content="Subham Agarwal" />
    <title>

      {% block title %}
        The Money App
      {% endblock title %}

    </title>

    {% block favicons %}
      <!-- <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png" />
      <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png" />
      <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png" />
      <link rel="icon" type="image/png" href="/favicon.ico" />
      <link rel="manifest" href="/site.webmanifest" />
      <link rel="mask-icon" href="/safari-pinned-tab.svg" color="#5bbad5" /> -->
      <meta name="msapplication-TileColor" content="#ffffff" />
      <meta name="theme-color" content="#ffffff" />
      <link rel="icon" href="{% static 'images/favicons/favicon.ico' %}" />
    {% endblock favicons %}

    {% block css %}
      <!-- Your stuff: Third-party CSS libraries go here -->
      <!-- This file stores project-specific CSS -->
      {% render_bundle "project" "css" %}
    {% endblock css %}

    {# Placed at the top of the document so pages load faster with defer #}

    {% block javascript %}
      <!-- Vendor dependencies bundled as one file -->
      {% render_bundle "vendors" "js" attrs="defer" %}
      <!-- place project specific Javascript in this file -->
      {% render_bundle "project" "js" attrs="defer" %}
    {% endblock javascript %}

    {% block inline_javascript_override %}
      <script>
        // On page load or when changing themes, best to add inline in `head` to avoid FOUC
        if (localStorage.getItem('color-theme') === 'dark' || (!('color-theme' in localStorage) && window.matchMedia('(prefers-color-scheme: dark)').matches)) {
          document.documentElement.classList.add('dark');
        } else {
          document.documentElement.classList.remove('dark')
        }
      </script>

      {% block inline_javascript %}
        {% comment %}
          Script tags with only code, no src (defer by default). To run
          with a "defer" so that you run inline code:
          <script>
            window.addEventListener('DOMContentLoaded', () => {
              /* Run whatever you want */
            });
          </script>
        {% endcomment %}
      {% endblock inline_javascript %}
    {% endblock inline_javascript_override %}

  </head>

  {% block body_override %}
    <body class=" 
      {% block body_class %} bg-gray-50 dark:bg-gray-800{% endblock body_class %}
       ">

      {% block body %}
      {% endblock body %}

      <!-- /container -->

      {% block modal %}
      {% endblock modal %}

    </body>
  {% endblock body_override %}

</html>

src/themoneyapp/templates/_layouts/main.html
{% extends "_layouts/base.html" %}

{% block body %}
  {{ block.super }}

  {% include "_partials/main_navbar.html" %}

  {% block main %}
    <main class="bg-gray-50 dark:bg-gray-900">
      <div class="container px-4 pt-24 mx-auto md:pt-32 lg:px-0 dark:bg-gray-900">

        {% block main_container %}
          {% block main_content %}
          {% endblock main_content %}
        {% endblock main_container %}

      </div>
    </main>
  {% endblock main %}

  {% if show_footer %}

    {% include "_partials/main_footer.html" %}

  {% endif %}
{% endblock body %}

src/themoneyapp/templates/_partials/dashboard_footer.html
<footer class="p-4 my-6 mx-4 bg-white rounded-lg shadow md:flex md:items-center md:justify-between md:p-6 xl:p-8 dark:bg-gray-800">
  <ul class="flex flex-wrap items-center mb-6 space-y-1 md:mb-0">
    <li>
      <a href="#"
         class="mr-4 text-sm font-normal text-gray-500 hover:underline md:mr-6 dark:text-gray-400">Terms and conditions</a>
    </li>
    <li>
      <a href="#"
         class="mr-4 text-sm font-normal text-gray-500 hover:underline md:mr-6 dark:text-gray-400">Privacy Policy</a>
    </li>
    <li>
      <a href="#"
         class="mr-4 text-sm font-normal text-gray-500 hover:underline md:mr-6 dark:text-gray-400">Licensing</a>
    </li>
    <li>
      <a href="#"
         class="mr-4 text-sm font-normal text-gray-500 hover:underline md:mr-6 dark:text-gray-400">Cookie Policy</a>
    </li>
    <li>
      <a href="#"
         class="text-sm font-normal text-gray-500 hover:underline dark:text-gray-400">Contact</a>
    </li>
  </ul>
  <div class="flex space-x-6 sm:justify-center">
    <a href="#"
       class="text-gray-500 hover:text-gray-900 dark:text-gray-400 dark:hover:text-white">
      <svg class="w-5 h-5"
           fill="currentColor"
           viewBox="0 0 24 24"
           aria-hidden="true">
        <path fill-rule="evenodd" d="M22 12c0-5.523-4.477-10-10-10S2 6.477 2 12c0 4.991 3.657 9.128 8.438 9.878v-6.987h-2.54V12h2.54V9.797c0-2.506 1.492-3.89 3.777-3.89 1.094 0 2.238.195 2.238.195v2.46h-1.26c-1.243 0-1.63.771-1.63 1.562V12h2.773l-.443 2.89h-2.33v6.988C18.343 21.128 22 16.991 22 12z" clip-rule="evenodd" />
      </svg>
    </a>
    <a href="#"
       class="text-gray-500 hover:text-gray-900 dark:text-gray-400 dark:hover:text-white">
      <svg class="w-5 h-5"
           fill="currentColor"
           viewBox="0 0 24 24"
           aria-hidden="true">
        <path fill-rule="evenodd" d="M12.315 2c2.43 0 2.784.013 3.808.06 1.064.049 1.791.218 2.427.465a4.902 4.902 0 011.772 1.153 4.902 4.902 0 011.153 1.772c.247.636.416 1.363.465 2.427.048 1.067.06 1.407.06 4.123v.08c0 2.643-.012 2.987-.06 4.043-.049 1.064-.218 1.791-.465 2.427a4.902 4.902 0 01-1.153 1.772 4.902 4.902 0 01-1.772 1.153c-.636.247-1.363.416-2.427.465-1.067.048-1.407.06-4.123.06h-.08c-2.643 0-2.987-.012-4.043-.06-1.064-.049-1.791-.218-2.427-.465a4.902 4.902 0 01-1.772-1.153 4.902 4.902 0 01-1.153-1.772c-.247-.636-.416-1.363-.465-2.427-.047-1.024-.06-1.379-.06-3.808v-.63c0-2.43.013-2.784.06-3.808.049-1.064.218-1.791.465-2.427a4.902 4.902 0 011.153-1.772A4.902 4.902 0 015.45 2.525c.636-.247 1.363-.416 2.427-.465C8.901 2.013 9.256 2 11.685 2h.63zm-.081 1.802h-.468c-2.456 0-2.784.011-3.807.058-.975.045-1.504.207-1.857.344-.467.182-.8.398-1.15.748-.35.35-.566.683-.748 1.15-.137.353-.3.882-.344 1.857-.047 1.023-.058 1.351-.058 3.807v.468c0 2.456.011 2.784.058 3.807.045.975.207 1.504.344 1.857.182.466.399.8.748 1.15.35.35.683.566 1.15.748.353.137.882.3 1.857.344 1.054.048 1.37.058 4.041.058h.08c2.597 0 2.917-.01 3.96-.058.976-.045 1.505-.207 1.858-.344.466-.182.8-.398 1.15-.748.35-.35.566-.683.748-1.15.137-.353.3-.882.344-1.857.048-1.055.058-1.37.058-4.041v-.08c0-2.597-.01-2.917-.058-3.96-.045-.976-.207-1.505-.344-1.858a3.097 3.097 0 00-.748-1.15 3.098 3.098 0 00-1.15-.748c-.353-.137-.882-.3-1.857-.344-1.023-.047-1.351-.058-3.807-.058zM12 6.865a5.135 5.135 0 110 10.27 5.135 5.135 0 010-10.27zm0 1.802a3.333 3.333 0 100 6.666 3.333 3.333 0 000-6.666zm5.338-3.205a1.2 1.2 0 110 2.4 1.2 1.2 0 010-2.4z" clip-rule="evenodd" />
      </svg>
    </a>
    <a href="#"
       class="text-gray-500 hover:text-gray-900 dark:text-gray-400 dark:hover:text-white">
      <svg class="w-5 h-5"
           fill="currentColor"
           viewBox="0 0 24 24"
           aria-hidden="true">
        <path d="M8.29 20.251c7.547 0 11.675-6.253 11.675-11.675 0-.178 0-.355-.012-.53A8.348 8.348 0 0022 5.92a8.19 8.19 0 01-2.357.646 4.118 4.118 0 001.804-2.27 8.224 8.224 0 01-2.605.996 4.107 4.107 0 00-6.993 3.743 11.65 11.65 0 01-8.457-4.287 4.106 4.106 0 001.27 5.477A4.072 4.072 0 012.8 9.713v.052a4.105 4.105 0 003.292 4.022 4.095 4.095 0 01-1.853.07 4.108 4.108 0 003.834 2.85A8.233 8.233 0 012 18.407a11.616 11.616 0 006.29 1.84" />
      </svg>
    </a>
    <a href="#"
       class="text-gray-500 hover:text-gray-900 dark:text-gray-400 dark:hover:text-white">
      <svg class="w-5 h-5"
           fill="currentColor"
           viewBox="0 0 24 24"
           aria-hidden="true">
        <path fill-rule="evenodd" d="M12 2C6.477 2 2 6.484 2 12.017c0 4.425 2.865 8.18 6.839 9.504.5.092.682-.217.682-.483 0-.237-.008-.868-.013-1.703-2.782.605-3.369-1.343-3.369-1.343-.454-1.158-1.11-1.466-1.11-1.466-.908-.62.069-.608.069-.608 1.003.07 1.531 1.032 1.531 1.032.892 1.53 2.341 1.088 2.91.832.092-.647.35-1.088.636-1.338-2.22-.253-4.555-1.113-4.555-4.951 0-1.093.39-1.988 1.029-2.688-.103-.253-.446-1.272.098-2.65 0 0 .84-.27 2.75 1.026A9.564 9.564 0 0112 6.844c.85.004 1.705.115 2.504.337 1.909-1.296 2.747-1.027 2.747-1.027.546 1.379.202 2.398.1 2.651.64.7 1.028 1.595 1.028 2.688 0 3.848-2.339 4.695-4.566 4.943.359.309.678.92.678 1.855 0 1.338-.012 2.419-.012 2.747 0 .268.18.58.688.482A10.019 10.019 0 0022 12.017C22 6.484 17.522 2 12 2z" clip-rule="evenodd" />
      </svg>
    </a>
    <a href="#"
       class="text-gray-500 hover:text-gray-900 dark:text-gray-400 dark:hover:text-white">
      <svg class="w-5 h-5"
           fill="currentColor"
           viewBox="0 0 24 24"
           aria-hidden="true">
        <path fill-rule="evenodd" d="M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10c5.51 0 10-4.48 10-10S17.51 2 12 2zm6.605 4.61a8.502 8.502 0 011.93 5.314c-.281-.054-3.101-.629-5.943-.271-.065-.141-.12-.293-.184-.445a25.416 25.416 0 00-.564-1.236c3.145-1.28 4.577-3.124 4.761-3.362zM12 3.475c2.17 0 4.154.813 5.662 2.148-.152.216-1.443 1.941-4.48 3.08-1.399-2.57-2.95-4.675-3.189-5A8.687 8.687 0 0112 3.475zm-3.633.803a53.896 53.896 0 013.167 4.935c-3.992 1.063-7.517 1.04-7.896 1.04a8.581 8.581 0 014.729-5.975zM3.453 12.01v-.26c.37.01 4.512.065 8.775-1.215.25.477.477.965.694 1.453-.109.033-.228.065-.336.098-4.404 1.42-6.747 5.303-6.942 5.629a8.522 8.522 0 01-2.19-5.705zM12 20.547a8.482 8.482 0 01-5.239-1.8c.152-.315 1.888-3.656 6.703-5.337.022-.01.033-.01.054-.022a35.318 35.318 0 011.823 6.475 8.4 8.4 0 01-3.341.684zm4.761-1.465c-.086-.52-.542-3.015-1.659-6.084 2.679-.423 5.022.271 5.314.369a8.468 8.468 0 01-3.655 5.715z" clip-rule="evenodd" />
      </svg>
    </a>
  </div>
</footer>
<p class="my-10 text-sm text-center text-gray-500">
  © 2024 <a href="#" class="hover:underline" target="_blank">Flowbite.com</a>. All rights reserved.
</p>

src/themoneyapp/templates/themoneyapp/index.html
{% extends "_layouts/dashboard.html" %}

{% block main_content %}
  <h1 class="mb-6 text-3xl text-green-800">Django + Tailwind CSS + Flowbite</h1>
  <div class="max-w-sm bg-white border border-gray-200 rounded-lg shadow-md dark:bg-gray-800 dark:border-gray-700">
    <a href="#">
      <img class="rounded-t-lg" src="/docs/images/blog/image-1.jpg" alt="" />
    </a>
    <div class="p-5">
      <a href="#">
        <h5 class="mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-white">
          Noteworthy technology
          acquisitions 2021
        </h5>
      </a>
      <p class="mb-3 font-normal text-gray-700 dark:text-gray-400">
        Here are the biggest enterprise technology
        acquisitions of 2021 so far, in reverse chronological order.
      </p>
      <a href="#"
         class="inline-flex items-center px-3 py-2 text-sm font-medium text-center text-white bg-green-700 rounded-lg hover:bg-green-800 focus:ring-4 focus:outline-none focus:ring-green-300 dark:bg-green-600 dark:hover:bg-green-700 dark:focus:ring-green-800">
        Read more
        <svg class="w-4 h-4 ml-2 -mr-1"
             fill="currentColor"
             viewBox="0 0 20 20"
             xmlns="http://www.w3.org/2000/svg">
          <path fill-rule="evenodd" d="M10.293 3.293a1 1 0 011.414 0l6 6a1 1 0 010 1.414l-6 6a1 1 0 01-1.414-1.414L14.586 11H3a1 1 0 110-2h11.586l-4.293-4.293a1 1 0 010-1.414z" clip-rule="evenodd" />
        </svg>
      </a>
    </div>
  </div>
{% endblock main_content %}

src/themoneyapp/templates/themoneyapp_users/user_detail.html
{% extends "themoneyapp/_base.html" %}

{% load static %}

{% block title %}
  User: {{ object.name }}
{% endblock title %}

{% block content %}
  <div class="container">
    <div class="row">
      <div class="col-sm-12">
        <h2>{{ object.name }}</h2>
      </div>
    </div>
    {% if object == request.user %}
      <!-- Action buttons -->
      <div class="row">
        <div class="col-sm-12">
          <a class="btn btn-primary"
             href="{% url 'themoneyapp_users:update' %}"
             role="button">My Info</a>
          <a class="btn btn-primary"
             href="{% url 'account_email' %}"
             role="button">E-Mail</a>
          <a class="btn btn-primary" href="{% url 'mfa_index' %}" role="button">MFA</a>
          <!-- Your Stuff: Custom user template urls -->
        </div>
      </div>
      <!-- End Action buttons -->
    {% endif %}
  </div>
{% endblock content %}

src/themoneyapp/templates/themoneyapp_users/user_form.html
{% extends "themoneyapp/_base.html" %}

{% block title %}
  {{ user.name }}
{% endblock title %}

{% block content %}
  <h1>{{ user.name }}</h1>
  <form class="form-horizontal"
        method="post"
        action="{% url 'themoneyapp_users:update' %}">
    {% csrf_token %}
    {{ form }}
    <div class="control-group">
      <div class="controls">
        <button type="submit" class="btn btn-primary">Update</button>
      </div>
    </div>
  </form>
{% endblock content %}